apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ if .Values.namespace }} {{ .Values.namespace }} {{ else }} {{ .Values.deployment.name }} {{ end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      chart: generic-helm
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        chart: generic-helm
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- .Values.deployment.initContainers | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.persistence.enabled .Values.configMap.enabled }}
      volumes:
        {{- if or .Values.persistence.enabled }}
        - name: default
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        - name: config
          configMap:
            name: {{ .Values.deployment.name }}
        {{- end }}
        {{- if .Values.persistence.additionalVolumes }}
          {{- .Values.persistence.additionalVolumes | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: default
            {{- if .Values.persistence.additionalMounts }}
              {{- .Values.persistence.additionalMounts | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{ if .Values.deployment.envVars }}
          env:
            {{ .Values.deployment.environmentVariables | toYaml | indent 12 | trim }}
          {{ end }}
          {{ if or .Values.deployment.requests .Values.deployment.limits }}
          resources:
            {{ if .Values.deployment.requests }}
            requests:
              {{ .Values.deployment.requests | toYaml | trim }}
            {{ end }}
            {{ if .Values.deployment.limits }}
            limits:
              {{ .Values.deployment.limits | toYaml | trim }}
            {{ end }}
          {{ end }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
              {{- if .Values.deployment.hostPort }}
              hostPort: {{ .Values.deployment.hostPort }}
              {{- end }}