image:
  repository: repository # repository of the image
  tag: tag # tag of the image
  imagePullPolicy: IfNotPresent

namespace: # namespace defaults to deployment name

deployment:
  replicas: 1
  name: default # name of the deployment, will also be the name of the service
  containerPort: 80
  envVars: {}
  #  - name: "ExampleKey"
  #    value: "ExampleValue"
  requests:
    # cpu: 50m
  limits:
    # cpu: 100m

service:
  enabled: true
  type: ClusterIP
  port: # default to container port

ingress:
  enabled: true
  annotations: {}
  tls:
  hosts:

persistence:
  enabled: false
  storageClass: local-storage
  existingClaim: ""
  mountPath: "/config"
  # if you need any additional volumes, you can define them here
  additionalVolumes: []
  # if you need any additional volume mounts, you can define them here
  additionalMounts: []

deploymentStrategy:
  type: RollingUpdate

configMap:
  enabled: true
  data: #{}
    test.conf: |
      test_allow true

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 60
